### ISSUE TITLE
One LED Stripe

### ISSUE THREAD

**Issue by leonardosalles** [sieuwe1/CortanaRoom#1]
Hi dude, thx for this awesome lib.

At this moment I am trying to make cortana works with a simple rgb led stripe, I developed the hardware by following the simple mode in [this tutorial](http://www.instructables.com/id/Use-Cortana-and-a-Arduino-to-Control-RGB-Leds-or-L/) and I noticed that you closed the CortanaRGB project and pretend to launch it on kickstarter, my question is if I can do the same as CortanaRGB with this lib and if I can follow the same hardware instructions, sorry for that but I am new to electronic, I am a very experienced developer but not too good with hardware 😂

It will be very good if you can help.

Thanks again!

**Comment by sieuwe1** [comment]
Hello Leonardo Salles


Sorry that i closed the Instructables. CortanRGB is going to launch this week on Kickstarter. The price will be 18$ and that encludes everything. So if you are interested in that check Kickstarter coming week. But if you want to build it yourself CortanaRoom also supports RGB ledstrips. So you can follow that instructions. Please note that i noticed that Microsoft changed how commands work in c#. I have as prefix please but this one is not allowed anymore in the guidelines. So this prefix needs to be changed in the code to for example Can.


Greetings Sieuwe




________________________________
Van: Leonardo Salles <notifications@github.com>
Verzonden: zaterdag 27 januari 2018 08:44
Aan: sieuwe1/CortanaRoom
CC: Subscribed
Onderwerp: [sieuwe1/CortanaRoom] One LED Stripe (#1)


Hi dude, thx for this awesome lib.

At this moment I am trying to make cortana works with a simple rgb led stripe, I developed the hardware by following the simple mode in this tutorial<http://www.instructables.com/id/Use-Cortana-and-a-Arduino-to-Control-RGB-Leds-or-L/> and I noticed that you closed the CortanaRGB project and pretend to launch it on kickstarter, my question is if I can do the same as CortanaRGB with this lib and if I can follow the same hardware instructions, sorry for that but I am new to electronic, I am a very experienced developer but not too good with hardware 😂

It will be very good if you can help.

Thanks again!

**Comment by leonardosalles** [comment]
Nice, so I can follow this scheme and connect RGB wires to Arduino pins without relays? And use CortanaRoom to control it? Last question I swear ;)

**Comment by sieuwe1** [comment]
Hi

Those are not relays haha. They are mosfets and are mandatory!! You may use relays but than the ledstrip wont fade on of off. It just turns on or off.

Ps i can give you the cortanaRGB software but then you will have to promise me that you wont share the program. Because i dont want to have competitors on my kickstarter. Once my kickstarter is done i will make the program open source again.

Greetings Sieuwe

Sent from my iPhone

On 27 Jan 2018, at 19:15, Leonardo Salles <notifications@github.com<mailto:notifications@github.com>> wrote:


Nice, so I can follow this scheme and connect RGB wires to Arduino pins without relays? And use CortanaRoom to control it? Last question I swear ;)

**Comment by leonardosalles** [comment]
@sieuwe1 it will be very nice if you can share, and sure I will not share your project, it is just because I am not good with electronics and I already bought the LED strip and the Arduino, so I don't want to waste my money. Can you contact me in my email(leosallestm@gmail.com) or send your one so I can shoot you a message? Oh, if you need anything I will be happy to help, I am good with websites, apps, photoshop and illustrator, maybe you will need a cool banner or website for your Kickstarter project hehehe ;)

Thanks again dude!
